In [24]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.svm import SVR

In [25]:
df=pd.read_csv("Hitters.csv")
df=df.dropna()
dms=pd.get_dummies(df[["League","Division","NewLeague"]])
y=df["Salary"]
X_=df.drop(["Salary","League","Division","NewLeague"],axis=1).astype("float64")
X=pd.concat([X_,dms[["League_N","Division_W","NewLeague_N"]]],axis=1)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [26]:
#model tahmin
svr_model=SVR(kernel="linear").fit(X_train,y_train)


In [27]:
svr_model

SVR(kernel='linear')

In [28]:
svr_model.intercept_

array([-43.67922349])

In [29]:
svr_model.coef_

array([[ -1.52738022,   8.41603061,  -0.62248071,  -2.91633012,
         -1.76348539,   4.05664922,   9.59333169,   0.01942209,
         -0.6897988 ,   0.0252315 ,   1.61711037,   0.83482588,
         -0.89443894,   0.25664992,   0.21656721,  -1.24359453,
          2.77033446, -14.48688936,   0.46266861]])

In [30]:
svr_model.predict(X_train)[0:20]

array([ 300.20165327,  169.45346536,  519.37057457,  562.50758983,
        686.05766456,  134.90025817, 1031.27559863, 1669.96844028,
        453.2960882 ,  927.19856441,  385.10041497,  619.59936945,
         95.17155184,  217.2909399 ,  709.53651445,  529.66791253,
        113.6501772 ,  493.00600411,  964.70800166,   56.07775115])

In [31]:
svr_model.predict(X_test)[0:20]

array([612.39761763, 556.79707247, 781.07233085, 306.47278181,
       498.52104898, 239.09656947, 548.47895581, 409.90166373,
       740.6978135 , 772.33272205, 591.92241557, 853.18292634,
       220.56304036, 296.14937981, 336.81972297, 507.7360041 ,
       678.75078902, 148.90098212, 951.97052412, 329.47046593])

In [32]:
# test
y_pred=svr_model.predict(X_test)
np.sqrt(mean_squared_error(y_test,y_pred))

364.68986308043964

In [33]:
##model turing

In [34]:
svr_model=SVR(kernel="linear")

In [35]:
svr_model

SVR(kernel='linear')

In [39]:
svr_params={"C":[0.1,0.5,1,3]}

In [40]:
from sklearn.model_selection import GridSearchCV

In [42]:
svr_cvmodel=GridSearchCV(svr_model,svr_params,cv=5).fit(X_train,y_train)

In [ ]:
svr_cvmodel.best_params_

In [ ]:
svr_cvmodel=GridSearchCV(svr_model,svr_params,cv=10,verbose=3,n_jobs=-1).fit(X_train,y_train)

In [43]:
svr_cvmodel.best_params_

{'C': 0.1}

In [44]:
svr_tuned=SVR(kernel="linear",C=0.5).fit(X_train,y_train)

In [45]:
y_pred=svr_tuned.predict(X_test)

In [46]:
np.sqrt(mean_squared_error(y_test,y_pred))

363.9574058834455